# Generated by Django 3.2.7 on 2021-11-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='student',
            new_name='students',
        ),
    ]
