# Generated by Django 3.2.7 on 2021-11-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
