# Generated by Django 3.2.7 on 2021-11-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
    ]
